### ISSUE TITLE
Get workflow warnings ironed out

### ISSUE THREAD

**Issue by cjfields** [h3abionet/HPCBio-Refgraph_pipeline#26]
@grendon I did a little cleanup today on the workflow to make the queue a little more configurable and to add a version of samtools that everyone can see. One small issue I found is that the first process emits some warnings:

```
$ nextflow run ~/HPCBio-Refgraph_pipeline/Refgraph.nf -c test.conf -qs 3 -resume
N E X T F L O W  ~  version 20.01.0
Launching `/home/a-m/hpcinstru04/HPCBio-Refgraph_pipeline/Refgraph.nf` [modest_borg] - revision: c718ae7d54
WARN: Access to undefined parameter `clusterAcct` -- Initialise it to a default value eg. `params.clusterAcct = some_value`
[skipped  ] process > prepare_genome   [100%] 1 of 1, stored: 1 ✔
executor >  slurm (2)
executor >  slurm (2)
[skipped  ] process > prepare_genome   [100%] 1 of 1, stored: 1 ✔
[7c/d859b4] process > extract_unmap    [  0%] 0 of 2
[-        ] process > trimming         -
[-        ] process > megahit_assemble -
[-        ] process > MultiQC_readPrep -                                                                                                                    [-        ] process > Assembly_metrics -
[skipping] Stored process > prepare_genome (GRCh38_full_analysis_set_plus_decoy_hla.fa)                                                                     WARN: Input tuple does not match input set cardinality declared by process `extract_unmap` -- offending value: /home/a-m/hpcinstru04/test-runs/first-pass/subset/NA18502.final.cram
```

I think this is b/c the channel for the CRAM files is generated using `Channel.fromPath`, which doesn't give a sample name like `Channel.fromFilePairs` does.  I can try fixing if you don't have time

**Comment by grendon** [comment]
will look into it.

**Comment by grendon** [comment]
I tested this snippet somewhere else and it solved the warning

<pre>
/*  this one is just to check how it is forming the tuples */
Channel
	    .fromFilePairs( params.samplePath, size: 3)
	    .view()

/* I expect three input files per sample R1, R2, I1 This channel declaration worked for me*/
Channel
	    .fromFilePairs( params.samplePath, size: 3)
	    .ifEmpty { error "Cannot find any reads matching: ${params.samplePath}" }
	    .into { Input_Ch1; Input_Ch2 }

clipped

process trimming {
    tag                    { name }
    ...

    input:
    set val(name), file(reads) from Input_Ch1 
    
    output:
    set val(name), file('*.trimmed.fq') optional true into trim_ch
    set val(name), file('*.json') optional true into multiqc_ch
    file '*' 

...

fastp --in1 ${reads[0]} --in2 ${reads[1]} --out1 ${name}.PE.R1.trimmed.fq  --out2 ${name}.PE.R2.trimmed.fq

...
}
</pre>

**Comment by cjfields** [comment]
Addressed.
