### ISSUE TITLE
Extraction of discordant, splitter and unmapped reads

### ISSUE THREAD

**Issue by yuantianhpc** [h3abionet/HPCBio-Refgraph_pipeline#33]
The following is a summary of the extraction of reads from 1000 genome data taking NA19238 as an example.

1. First convert cram file to bam file with samtools:
samtools view -T GRCh38_full_analysis_set_plus_decoy_hla.fa -b -o NA19238.bam NA19238.final.cram

2. Sort bam file with samtools:
samtools sort -o NA19238_sort_read.bam -n NA19238.bam

3. Convert bam file to sam file with samtools:
samtools view -h -o NA19238_sort_read.sam NA19238_sort_read.bam

4. Extract different types of reads with samblaster:
samblaster -i NA19238_sort_read.sam -d NA19238_discordant.bam -s NA19238_splitter.bam -u NA19238_unmapped.fastq -o /dev/null

5. Convert bam files to fastq files with samtools:
samtools fastq NA19238_discordant.bam -1 NA19238_discordant_R1.fastq -2 NA19238_discordant_R2.fastq
samtools fastq NA19238_splitter.bam -1 NA19238_splitter_R1.fastq -2 NA19238_splitter_R2.fastq

From 1 to 3, each step takes 2-3 hours; step 4 takes about 30 minutes; step 5 less than 30 minutes.
The following steps will be trimming, assembly, and removing contaminant reads.

**Comment by cjfields** [comment]
The key reads we needed were from clipped reads, which were intermixed with unmapped reads in Samblaster output and lacked their (possibly useful) mate.  We now include these both using a custom Python script and pysam.
