### ISSUE TITLE
Merge forks back into main branch

### ISSUE THREAD

**Issue by cjfields** [h3abionet/HPCBio-Refgraph_pipeline#34]
We have several forks that need to be merged back into `master`.

**Comment by cjfields** [comment]
Small list:

- [x] Kim
- [x] Gloria
- [x] Yuan
- [x] Mine

**Comment by cjfields** [comment]
All code now merged back

**Comment by NeginValizadegan** [comment]
Thanks! Do I still update changes to NV?

**Comment by cjfields** [comment]
@NeginValizadegan go ahead and keep the code on `NV` separate for now.
