### ISSUE TITLE
Containerization of tools

### ISSUE THREAD

**Issue by cjfields** [h3abionet/HPCBio-Refgraph_pipeline#5]
@yuantianhpc when you have time, we'll need a list of tools here that can be containerized.  Can use the task list (check box) in the above so anyone working on this can help generate them or point to new ones.

**Comment by cjfields** [comment]
Hi @yuantianhpc can you add a list of tools that we can prioritize for containerization here?  Off the top of my head I can think of:

- samtools
- FASTQC
- MEGAHIT
- Kraken2
- MaSurCA

Are there others?

**Comment by yuantianhpc** [comment]
> Hi @yuantianhpc can you add a list of tools that we can prioritize for containerization here? Off the top of my head I can think of:
> 
> * samtools
> * FASTQC
> * MEGAHIT
> * Kraken2
> * MaSurCA
> 
> Are there others?

The ones you listed above contain all in the current pipeline. Thank you! We may add trim tools to it, Trimmomatic and fastp.

**Comment by cjfields** [comment]
Now added to the Hackathon (along with some additional tools):

https://docs.google.com/spreadsheets/d/1y3yj1TiFjra5D2Pvmay2IeU-sfOkZmN6b_POEPtEEuw/edit?usp=sharing
